/* Casca do Espaço: cena, navegação, sensor do telefone e pausa de animações.
   As funções da Nebula (conversa, casa, projetos, mídia, telefone, terminal)
   ficam em nebula-app.js e conversam com as APIs reais do painel. */
const $=s=>document.querySelector(s);let current='chat',angle=0,targetAngle=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches;
let sensorEnabled=false,baseline=null,sensorTimer,tx=0,ty=0,sx=0,sy=0;
const ORBIT_STEP=.58,ORBIT_QUEUE=ORBIT_STEP*2;
function advanceRight(){targetAngle=Math.min(angle+ORBIT_QUEUE,Math.max(targetAngle,angle)+ORBIT_STEP);}
const SCENE_KEY='nebula-scene-v6';
function readScene(){try{const s=JSON.parse(sessionStorage.getItem(SCENE_KEY));return s&&s.version===6?s:null;}catch{return null;}}
const savedScene=readScene();
if(savedScene){angle=Number.isFinite(savedScene.angle)?savedScene.angle:0;targetAngle=Number.isFinite(savedScene.targetAngle)?savedScene.targetAngle:angle;sx=tx=Math.max(-13,Math.min(13,Number(savedScene.sx)||0));sy=ty=Math.max(-10,Math.min(10,Number(savedScene.sy)||0));if(typeof savedScene.paused==='boolean')paused=paused||savedScene.paused;}
function saveScene(){try{sessionStorage.setItem(SCENE_KEY,JSON.stringify({version:6,time,angle,targetAngle,sx,sy,paused,view:current}));}catch{}}
function stopSensor(){sensorEnabled=false;baseline=null;tx=ty=0;clearTimeout(sensorTimer);window.removeEventListener('deviceorientation',onOrientation);$('#gyro').setAttribute('aria-pressed','false');$('#gyro').textContent='◎ Movimento do telefone';}
function onOrientation(e){if(document.hidden||!Number.isFinite(e.beta)||!Number.isFinite(e.gamma))return;clearTimeout(sensorTimer);if(!baseline){baseline={b:e.beta,g:e.gamma};$('#sensor-status').textContent='Movimento ativado. Incline o telefone suavemente.';setTimeout(()=>$('#sensor-status').textContent='',3500);return;}const delta=(a,b)=>((a-b+540)%360)-180;const orientation=(screen.orientation?.angle||0)*Math.PI/180;const dx=delta(e.gamma,baseline.g)/25,dy=delta(e.beta,baseline.b)/25;baseline={b:e.beta,g:e.gamma};if(paused)return;tx=Math.max(-13,Math.min(13,tx+(dx*Math.cos(orientation)+dy*Math.sin(orientation))*13));ty=Math.max(-10,Math.min(10,ty+(dy*Math.cos(orientation)-dx*Math.sin(orientation))*10));}
$('#gyro').onclick=async()=>{if(sensorEnabled){stopSensor();$('#sensor-status').textContent='Movimento desativado.';return}if(paused){$('#sensor-status').textContent='Retome as animações pelo botão no topo antes de ativar o sensor.';return}if(!window.DeviceOrientationEvent){$('#sensor-status').textContent='Este navegador não disponibiliza o sensor de orientação.';return}try{if(typeof DeviceOrientationEvent.requestPermission==='function'){const permission=await DeviceOrientationEvent.requestPermission();if(permission!=='granted'){ $('#sensor-status').textContent='Permissão não concedida. A interface continua funcionando sem o sensor.';return}}sensorEnabled=true;baseline=null;$('#gyro').setAttribute('aria-pressed','true');$('#gyro').textContent='◎ Movimento ativado';$('#sensor-status').textContent='Aguardando o sensor…';window.addEventListener('deviceorientation',onOrientation,{passive:true});sensorTimer=setTimeout(()=>{stopSensor();$('#sensor-status').textContent='Nenhum sinal recebido. O sensor pode estar indisponível ou bloqueado neste navegador.'},6500)}catch{stopSensor();$('#sensor-status').textContent='Não foi possível ativar o sensor neste navegador.'}};
screen.orientation?.addEventListener('change',()=>baseline=null);document.addEventListener('visibilitychange',()=>{baseline=null;last=0;clearTimeout(sensorTimer);if(document.hidden)saveScene();});window.addEventListener('pagehide',saveScene);window.addEventListener('pageshow',()=>{baseline=null;last=0;});

const viewListeners=[];
function navigate(view,animate=true){if(!document.getElementById(view))return;current=view;if(animate)advanceRight();document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===view));document.querySelectorAll('.sidebar button,.mobile-nav [data-view],#orbit-menu [data-view]').forEach(el=>{const active=el.dataset.view===(view==='workspace'?'projects':view);el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});$('#mobile-menu-toggle').classList.toggle('active',!['chat','dupla','casa'].includes(view));toggleMenu(false);if(animate)window.scrollTo({top:0,behavior:'instant'});for(const listener of viewListeners){try{listener(view);}catch(error){console.warn('Nebula: falha ao preparar a seção.',error);}}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));$('.brand').onclick=e=>{e.preventDefault();navigate('chat')};
let menuOpener=null;
function toggleMenu(open,animate=false){if(open)menuOpener=document.activeElement;if(animate)advanceRight();$('#orbit-menu').hidden=!open;$('#menu-backdrop').hidden=!open;$('#orbit-toggle').setAttribute('aria-expanded',String(open));$('#mobile-menu-toggle').setAttribute('aria-expanded',String(open));document.body.classList.toggle('navigation-open',open);if(open)$('#orbit-menu button').focus();else if(menuOpener&&$('#orbit-menu').contains(document.activeElement))menuOpener.focus();}
$('#mobile-menu-toggle').onclick=()=>toggleMenu($('#orbit-menu').hidden);
$('#orbit-toggle').onclick=()=>toggleMenu($('#orbit-menu').hidden,true);$('#menu-backdrop').onclick=()=>toggleMenu(false,true);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#orbit-menu').hidden){toggleMenu(false,true);menuOpener?.focus()}});
let touchStart;$('#orbit-toggle').addEventListener('pointerdown',e=>touchStart=e.clientY);$('#orbit-toggle').addEventListener('pointerup',e=>{if(touchStart-e.clientY>20)toggleMenu(true)});
function syncMotion(){document.body.classList.toggle('paused',paused);$('#motion').textContent=paused?'▷':'Ⅱ';$('#motion').setAttribute('aria-label',paused?'Retomar animações':'Pausar animações')}syncMotion();$('#motion').onclick=()=>{paused=!paused;syncMotion();if(paused)draw(performance.now())};
// Layered noise volumes projected from world space. Camera motion changes depth,
// not the position of a flat background. The UI shares one slowly evolving hue.
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',advanceRight));
const canvas=$('#cosmos'),ctx=canvas.getContext('2d');
let w=innerWidth,h=innerHeight,dpr=1,last=0,time=Math.max(0,Math.min(Number(savedScene?.time)||0,1e12)),hue=215,lastTint=-1,lastSave=time;
const volumeCanvas=document.createElement('canvas');volumeCanvas.id='nebula-volume';volumeCanvas.setAttribute('aria-hidden','true');canvas.before(volumeCanvas);const volume=window.NebulaVolume?.create(volumeCanvas);if(!volume)volumeCanvas.remove();
let rngState=73421;function seededRandom(){rngState=(Math.imul(rngState,1664525)+1013904223)>>>0;return rngState/4294967296;}
const stars=Array.from({length:320},(_,i)=>{const bright=i%17===0;return{x:seededRandom(),y:seededRandom(),r:bright?1.15+seededRandom()*.6:.35+seededRandom()*.65,a:bright?.65+seededRandom()*.25:.16+seededRandom()*.4,phase:seededRandom()*Math.PI*2,speed:.00035+seededRandom()*.00045,depth:.5+seededRandom(),bright};});
function drawStars(cameraX,cameraY){const yaw=-angle*.22+sx*.002,focal=h/(2*.55);for(const s of stars){const azimuth=s.x*Math.PI*2,radius=2200/s.depth,wx=Math.sin(azimuth)*radius-cameraX,wz=Math.cos(azimuth)*radius;const z=wz*Math.cos(yaw)+wx*Math.sin(yaw);if(z<90)continue;const x=w*.5+(wx*Math.cos(yaw)-wz*Math.sin(yaw))*focal/z,y=h*.44+((s.y-.5)*radius*2-cameraY)*focal/z;if(x< -12||x>w+12||y< -12||y>h+12)continue;const shimmer=.8+.2*Math.sin(time*s.speed+s.phase);const quietCenter=(Math.abs(x-w*.5)<w*.25&&Math.abs(y-h*.48)<h*.16)?.7:1;const alpha=s.a*shimmer*quietCenter;if(s.bright){const radius=s.r*6,halo=ctx.createRadialGradient(x,y,0,x,y,radius);halo.addColorStop(0,'rgba(230,239,255,'+(alpha*.35)+')');halo.addColorStop(.28,'rgba(209,225,255,'+(alpha*.1)+')');halo.addColorStop(1,'rgba(209,225,255,0)');ctx.fillStyle=halo;ctx.fillRect(x-radius,y-radius,radius*2,radius*2);}ctx.fillStyle='rgba(237,243,255,'+alpha+')';ctx.beginPath();ctx.arc(x,y,s.r,0,Math.PI*2);ctx.fill();}}
function hash(x,y){const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n)}
function noise(x,y){const ix=Math.floor(x),iy=Math.floor(y);let fx=x-ix,fy=y-iy;fx=fx*fx*(3-2*fx);fy=fy*fy*(3-2*fy);const a=hash(ix,iy),b=hash(ix+1,iy),c=hash(ix,iy+1),d=hash(ix+1,iy+1);return a+(b-a)*fx+(c-a)*fy+(a-b-c+d)*fx*fy}
function texture(seed){const c=document.createElement('canvas');c.width=c.height=160;const g=c.getContext('2d'),im=g.createImageData(160,160);for(let y=0;y<160;y++)for(let x=0;x<160;x++){const u=(x-80)/80,v=(y-80)/80;let n=0,amp=.55,f=2.3;for(let j=0;j<4;j++){n+=noise(u*f+seed,v*f+seed*.63)*amp;amp*=.5;f*=2.1}const edge=Math.pow(Math.max(0,1-u*u-v*v),2);const density=Math.pow(Math.max(0,n-.20),1.15)*edge;const i=(y*160+x)*4;im.data[i]=im.data[i+1]=im.data[i+2]=255;im.data[i+3]=density*220;}g.putImageData(im,0,0);return c}
const textures=[texture(4),texture(17),texture(29)];const tinted=Array.from({length:6},()=>{const c=document.createElement('canvas');c.width=c.height=160;return c});
// Clouds surround a quiet central corridor at staggered depths.
const clouds=Array.from({length:64},(_,i)=>{const azimuth=hash(i,1)*Math.PI*2,radius=650+hash(i,3)*1700;return{x:Math.sin(azimuth)*radius,y:(hash(i,2)-.5)*1400,z:Math.cos(azimuth)*radius,size:500+hash(i,4)*430,rotation:hash(i,5)*6.28,texture:i%6,phase:hash(i,6)*6.28,sway:30+hash(i,7)*46,rate:.00007+hash(i,8)*.00006}});
function tintClouds(){const step=Math.round(hue);if(step===lastTint)return;lastTint=step;const offsets=[-14,-7,0,7,14,3],lights=[36,48,58,43,53,65];for(let i=0;i<tinted.length;i++){const g=tinted[i].getContext('2d');g.clearRect(0,0,160,160);g.globalCompositeOperation='source-over';g.drawImage(textures[i%textures.length],0,0);g.globalCompositeOperation='source-in';const tone=Math.max(215,Math.min(360,step+offsets[i]));const light=lights[i],saturation=54+(i%3)*9;const pigment=g.createRadialGradient(57+i*5,60,8,80,80,100);pigment.addColorStop(0,'hsl('+tone+' '+saturation+'% '+light+'%)');pigment.addColorStop(.5,'hsl('+Math.max(215,Math.min(360,tone+8))+' '+(saturation+4)+'% '+(light-9)+'%)');pigment.addColorStop(1,'hsl('+tone+' '+saturation+'% '+Math.max(20,light-22)+'%)');g.fillStyle=pigment;g.fillRect(0,0,160,160);}}
function resize(){w=innerWidth;h=innerHeight;dpr=Math.min(devicePixelRatio,1.25);canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}window.addEventListener('resize',resize);
function draw(){if(!ctx)return;hue=215+145*(.5-.5*Math.cos(time*Math.PI/90000));document.documentElement.style.setProperty('--accent-hue',hue.toFixed(1));ctx.clearRect(0,0,w,h);if(volume){volume.draw(time,angle,sx,sy,w,h);drawMeteor();return;}tintClouds();const cameraX=sx*7,cameraY=sy*6+Math.sin(time*.00004)*9,cameraZ=Math.sin(time*.000016)*90;const yaw=-angle*.22+sx*.002;const focal=h/(2*.55);drawStars(cameraX,cameraY);
const projected=clouds.map(p=>{const drift=time*p.rate+p.phase;const bob=Math.sin(drift)*p.sway;let z=p.z-cameraZ+Math.cos(drift*.77)*p.sway*.6;const x=p.x-cameraX+Math.cos(drift)*p.sway;return{p,bob,z:z*Math.cos(yaw)+x*Math.sin(yaw),x:x*Math.cos(yaw)-z*Math.sin(yaw)}}).sort((a,b)=>b.z-a.z);
ctx.globalCompositeOperation='screen';for(const item of projected){const {p,z,x,bob}=item;if(z<90)continue;const scale=focal/z,px=w*.5+x*scale,py=h*.44+(p.y+bob-cameraY)*scale;const size=p.size*scale;const fade=Math.min(1,(z-90)/260)*Math.min(1,(2520-z)/300);ctx.globalAlpha=.79*fade;ctx.save();ctx.translate(px,py);ctx.rotate(p.rotation+Math.sin(time*.00011+p.rotation)*.07);ctx.drawImage(tinted[p.texture],-size/2,-size/2,size,size);ctx.restore();}ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';
drawMeteor();}
function drawMeteor(){const meteor=time%97000;if(meteor>94000&&meteor<94900){const t=(meteor-94000)/900,x=w*.8-t*w*.25,y=h*.15+t*h*.2;const g=ctx.createLinearGradient(x,y,x+65,y-30);g.addColorStop(0,'#d5d8fa70');g.addColorStop(1,'#d5d8fa00');ctx.strokeStyle=g;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+65,y-30);ctx.stroke()}}
function tick(now){requestAnimationFrame(tick);if(document.hidden){last=0;return;}if(!last){last=now;draw();return;}if(now-last<40)return;const dt=Math.min(now-last,60);last=now;if(!paused){time+=dt;const ease=1-Math.exp(-dt/420);angle+=(targetAngle-angle)*ease;sx+=(tx-sx)*ease;sy+=(ty-sy)*ease;draw();if(time-lastSave>1500){saveScene();lastSave=time;}}else if(Math.abs(targetAngle-angle)>.01){angle=targetAngle;draw();}}

// Ponte para a camada de funções: navegar, reagir a trocas de seção e girar a cena.
window.NebulaShell={
  navigate,
  advanceRight,
  get view(){return current;},
  onView(listener){viewListeners.push(listener);},
};

if(savedScene?.view&&document.getElementById(savedScene.view)&&savedScene.view!=='workspace'){navigate(savedScene.view,false);}
targetAngle=Math.max(angle,targetAngle);
resize();requestAnimationFrame(tick);
